import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { useNavigate } from "react-router-dom";
import type { GeneratedScript } from "@/lib/gemini";
import ScriptHero from "@/components/ScriptHero";
import ScriptFrame from "@/components/ScriptFrame";
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel";

/**
 * A component that renders a script generated by the AI model based on the user-provided prompt.
 * If no script is generated, it renders a message with a button to go back to the prompt.
 * If a script is generated, it renders a hero section, a section with the script info (title, duration, and buttons to go back to the prompt and generate frames),
 * and a section with the frames of the script. The frames are rendered as a list of ScriptFrame components.
 */
const Script = () => {
  const [generatedScript, setGeneratedScript] = useState<GeneratedScript | null>(null);
  const [generatedImages, setGeneratedImages] = useState<string[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [statusMessage, setStatusMessage] = useState('');
  const navigate = useNavigate();

  useEffect(() => {
    const storedScript = localStorage.getItem('generatedScript');
    if (storedScript) {
      setGeneratedScript(JSON.parse(storedScript));
    }
    const storedImages = localStorage.getItem('generatedImages');
    if (storedImages) {
      setGeneratedImages(JSON.parse(storedImages));
    }
  }, []);

  /**
   * Navigate back to the prompt page.
   */
  const handleBackToPrompt = () => {
    navigate('/prompt');
  };

  /**
   * Updates the script with a new frame value.
   * @param index - The index of the frame to update.
   * @param field - The field to update in the frame (e.g. "visual", "voiceover", etc.).
   * @param value - The new value for the field.
   */
  const handleFrameChange = (index: number, field: string, value: string) => {
    const updatedScript = {...generatedScript};
    updatedScript.frames[index][field] = value;
    setGeneratedScript(updatedScript);
    localStorage.setItem('generatedScript', JSON.stringify(updatedScript));
  };

  if (!generatedScript) {
    return (
      <main className="min-h-screen bg-background">
        <div className="container mx-auto px-4 py-16">
          <div className="text-center space-y-4">
            <h2 className="text-2xl font-bold text-foreground">No script generated yet.</h2>
            <Button 
              onClick={handleBackToPrompt}
              className="bg-gradient-to-r from-primary to-secondary hover:opacity-90 transition-all duration-300"
            >
              Back to Prompt
            </Button>
          </div>
        </div>
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-background relative overflow-hidden flex flex-col">
      {/* Hero Section */}
      <ScriptHero />
      
      {/* Main Content */}
      <div className="container mx-auto px-4 flex-1 flex flex-col">
        {/* Script Info */}
        <div className="max-w-4xl mx-auto mb-4">
          <div className="flex justify-between items-center gap-4 flex-wrap">
            <div>
              <h2 className="text-2xl font-bold text-foreground">
                {generatedScript?.title}
              </h2>
              <p className="text-muted-foreground">
                {generatedScript?.duration}
              </p>
            </div>
            
            {/* Navigation Buttons */}
            <div className="flex gap-4">
              <Button
                variant="outline"
                onClick={handleBackToPrompt}
                className="group transition-all duration-300 hover:bg-primary/10 hover:text-primary border-primary/20"
              >
                <span className="mr-2 transform group-hover:-translate-x-1 transition-transform">←</span>
                Back to Prompt
              </Button>
              <Button
                className="bg-gradient-to-r from-primary to-secondary hover:opacity-90"
                disabled={isLoading}
                onClick={async () => {
                  if (!generatedScript) return;
                  setIsLoading(true);
                  setStatusMessage('Generating Frames...');
                  const images: string[] = [];
                  for (let i = 0; i < generatedScript.frames.length; i++) {
                    const frame = generatedScript.frames[i];
                    setStatusMessage(`Fetching image ${i + 1}/${generatedScript.frames.length}`);
                    const response = await fetch('http://localhost:3000/api/generate-image', {
                      method: 'POST',
                      headers: {
                        'Content-Type': 'application/json',
                      },
                      body: JSON.stringify({ prompt: frame.visual }),
                    });

                    const data = await response.json();
                    images.push(`data:image/png;base64,${data.data[0].b64_json}`);

                    // Delay for 10 seconds to avoid rate limiting
                    await new Promise(resolve => setTimeout(resolve, 10000));
                  }
                  setGeneratedImages(images);
                  localStorage.setItem('generatedImages', JSON.stringify(images));
                  setIsLoading(false);
                  setStatusMessage('');
                }}
              >
                {isLoading ? statusMessage : "Generate Frames →"}
              </Button>
            </div>
          </div>
        </div>

        {/* Frames */}
        <div className="flex-1 relative">
          <Carousel className="w-4/5 mx-auto h-[calc(100vh-300px)]">
            <CarouselContent>
              {generatedScript?.frames.map((frame, index) => (
                <CarouselItem key={index} className="flex justify-center items-start">
                  <ScriptFrame
                    index={index}
                    frame={frame}
                    onChange={(field, value) => handleFrameChange(index, field, value)}
                    generatedImage={generatedImages[index]}
                  />
                </CarouselItem>
              ))}
            </CarouselContent>
            <CarouselPrevious className="hover:bg-primary/10 hover:text-primary border-primary/20" />
            <CarouselNext className="hover:bg-primary/10 hover:text-primary border-primary/20" />
          </Carousel>
        </div>
      </div>
    </main>
  );
};

export default Script;
