import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { useNavigate } from "react-router-dom";
import type { GeneratedScript, GeneratedThread } from "@/lib/gemini";
import TweetThread from "@/components/TweetThread";

/**
 * A component that renders a thread generated by the AI model based on the user-provided prompt.
 * If no script is generated, it renders a message with a button to go back to the prompt.
 */
const Thread = () => {
  const [generatedScript, setGeneratedScript] = useState<GeneratedScript | null>(null);
  const [generatedImages, setGeneratedImages] = useState<string[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [statusMessage, setStatusMessage] = useState('');
  const [isPublishing, setIsPublishing] = useState(false);
  const navigate = useNavigate();

  const backendUrl = import.meta.env.VITE_BACKEND_URL;

  useEffect(() => {
    const storedScript = localStorage.getItem('generatedScript');
    if (storedScript) {
      setGeneratedScript(JSON.parse(storedScript));
    }

    const storedImages = localStorage.getItem('generatedThreadImages');
    if (storedImages) {
      setGeneratedImages(JSON.parse(storedImages));
    }
  }, []);

  useEffect(() => {
    if (!generatedScript) return;

    const fetchImages = async () => {
      setIsLoading(true);
      setStatusMessage('Fetching Images...');
      const images: string[] = [];
      for (let i = 0; i < generatedScript.threads.length; i++) {
        const thread = generatedScript.threads[i];
        setStatusMessage(`Fetching image ${i + 1}/${generatedScript.threads.length}`);
        try {
          const response = await fetch(`${backendUrl}/api/generate-image`, {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({ prompt: thread.image_prompt }),
          });

          const data = await response.json();
          images.push(`data:image/png;base64,${data.data[0].b64_json}`);
        } catch (error) {
          console.error("Error fetching image:", error);
          images.push(""); // Push an empty string as a placeholder in case of error
        }

        // Delay for 10 seconds to avoid rate limiting
        await new Promise(resolve => setTimeout(resolve, 10000));
      }
      setGeneratedImages(images);
      localStorage.setItem('generatedThreadImages', JSON.stringify(images));
      setIsLoading(false);
      setStatusMessage('');
    };

    if (generatedImages.length === 0 && generatedScript.threads.length > 0) {
      fetchImages();
    }
  }, [generatedScript, backendUrl, generatedImages]);

  /**
   * Navigate back to the prompt page.
   */
  const handleBackToPrompt = () => {
    navigate('/create-x-post');
  };

  const handlePublish = async () => {
    setIsPublishing(true);
    setStatusMessage("Publishing Tweets...");
    try {
      if (!generatedScript) return;

      for (let i = 0; i < generatedScript.threads.length; i++) {
        const thread = generatedScript.threads[i];
        setStatusMessage(`Publishing tweet ${i + 1}/${generatedScript.threads.length}`);

        const response = await fetch(`${backendUrl}/api/postTweet`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            text: thread.tweet,
            imageData: generatedImages[i]?.split(',')[1] || null, // Extract base64 data
          }),
        });

        if (!response.ok) {
          console.error("Error posting tweet:", response.statusText);
        }

        // Delay for 5 seconds between tweets
        await new Promise(resolve => setTimeout(resolve, 5000));
      }

      setStatusMessage("Tweets published successfully!");
    } catch (error) {
      console.error("Error publishing tweets:", error);
      setStatusMessage("Failed to publish tweets.");
    } finally {
      setIsPublishing(false);
    }
  };

  const tweets = generatedScript?.threads?.map((thread: GeneratedThread, index) => ({
    name: "ThreadGenie",
    username: "kalyan_konudula",
    content: thread.tweet,
    timestamp: "2m",
    imageUrl: generatedImages[index] || "", // Use fetched image or empty string if not available
  }));

  return (
    <main className="min-h-screen bg-background">
      <section className="h-screen flex flex-col">
        {/* Script Info */}
        <div className="container mx-auto px-4 py-6">
          <div className="flex justify-between items-center gap-4 flex-wrap">
            <div>
              <h2 className="text-2xl font-bold text-foreground">
                {generatedScript?.title}
              </h2>
            </div>

            {/* Navigation Buttons */}
            <div className="flex gap-4">
              <Button
                variant="outline"
                onClick={handleBackToPrompt}
                className="group transition-all duration-300 hover:bg-primary/10 hover:text-primary border-primary/20"
              >
                <span className="mr-2 transform group-hover:-translate-x-1 transition-transform">←</span>
                Back to Prompt
              </Button>
            </div>
          </div>
        </div>

        {isLoading && (
          <div className="w-full bg-gray-200 text-center py-2">
            {statusMessage}
          </div>
        )}

        {/* Threads */}
        <div className="flex-1 relative">
          {tweets && <TweetThread tweets={tweets} />}
        </div>

        <div className="container mx-auto px-4 py-6">
          <Button
            disabled={isLoading || generatedImages.length === 0 || isPublishing}
            onClick={handlePublish}
            className="bg-gradient-to-r from-primary to-secondary hover:opacity-90"
          >
            {isPublishing ? statusMessage : "Publish to Twitter"}
          </Button>
        </div>
      </section>
    </main>
  );
};

export default Thread;