import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { useNavigate } from "react-router-dom";
import type { GeneratedScript, GeneratedThread } from "@/lib/gemini";
import TweetThread from "@/components/TweetThread";

/**
 * A component that renders a thread generated by the AI model based on the user-provided prompt.
 * If no script is generated, it renders a message with a button to go back to the prompt.
 */
const Thread = () => {
  const [generatedScript, setGeneratedScript] = useState<GeneratedScript | null>(null);
  const [generatedImages, setGeneratedImages] = useState<(string | null)[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [statusMessage, setStatusMessage] = useState('');
  const [isPublishing, setIsPublishing] = useState(false);
  const [threadReport, setThreadReport] = useState<any[]>([]);
  const navigate = useNavigate();

  const backendUrl = import.meta.env.VITE_BACKEND_URL;

  useEffect(() => {
    const storedScript = localStorage.getItem('generatedScript');
    if (storedScript) {
      setGeneratedScript(JSON.parse(storedScript));
    }

    const storedImages = localStorage.getItem('generatedThreadImages');
    if (storedImages) {
      setGeneratedImages(JSON.parse(storedImages));
    }
  }, []);

  useEffect(() => {
    if (!generatedScript) return;

    const fetchImages = async () => {
      setIsLoading(true);
      setStatusMessage('Fetching Images...');
      const images: (string | null)[] = Array(generatedScript.threads.length).fill(null);
      setGeneratedImages(images);

      for (let i = 0; i < generatedScript.threads.length; i++) {
        const thread = generatedScript.threads[i];
        setStatusMessage(`Fetching image ${i + 1}/${generatedScript.threads.length}`);
        try {
          const response = await fetch(`${backendUrl}/api/generate-image`, {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({ prompt: thread.image_prompt }),
          });

          const data = await response.json();
          const imageData = `data:image/png;base64,${data.data[0].b64_json}`;

          setGeneratedImages((prev) => {
            const updated = [...prev];
            updated[i] = imageData;
            return updated;
          });
        } catch (error) {
          console.error("Error fetching image:", error);
          setGeneratedImages((prev) => {
            const updated = [...prev];
            updated[i] = null;
            return updated;
          });
        }

        // Delay for 10 seconds to avoid rate limiting
        await new Promise(resolve => setTimeout(resolve, 10000));
      }
      setIsLoading(false);
      setStatusMessage('');
    };

    if (generatedScript.threads.length > 0) {
      fetchImages();
    }
  }, [generatedScript, backendUrl]);

  /**
   * Navigate back to the prompt page.
   */
  const handleBackToPrompt = () => {
    navigate('/create-x-post');
  };

  const handlePublish = async () => {
    setIsPublishing(true);
    setStatusMessage("Publishing Tweets...");
    try {
      if (!generatedScript) return;

      const tweets = generatedScript.threads.map((thread, index) => ({
        text: thread.tweet,
        imageData: generatedImages[index]?.split(',')[1] || null, // Extract base64 data
      }));

      const response = await fetch(`${backendUrl}/api/postTweetThread`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ tweets }),
      });

      const data = await response.json();

      if (!response.ok) {
        console.error("Error posting tweet:", response.statusText);
        setStatusMessage(`Failed to publish tweets: ${response.statusText}`);
      } else {
        setStatusMessage("Tweets published successfully!");
        setThreadReport(data.threadReport);
      }
    } catch (error) {
      console.error("Error publishing tweets:", error);
      setStatusMessage("Failed to publish tweets.");
      setThreadReport([{ success: false, error: error.message }]);
    } finally {
      setIsPublishing(false);
    }
  };

  const tweets = generatedScript?.threads?.map((thread: GeneratedThread, index) => ({
    name: "ThreadGenie",
    username: "ThreadGenieAI",
    content: thread.tweet,
    timestamp: "2m",
    imageUrl: generatedImages[index] ?? null
  })) || [];

  return (
    <main className="min-h-screen bg-background">
      <section className="h-screen flex flex-col">
        {/* Action Bar */}
        <div className="container mx-auto py-3 px-4">
          <div className="flex flex-col md:flex-row items-center justify-between gap-2">
            <Button
              variant="outline"
              onClick={handleBackToPrompt}
              className="group transition-all duration-300 hover:bg-primary/10 hover:text-primary border-primary/20"
            >
              <span className="mr-2 transform group-hover:-translate-x-1 transition-transform">←</span>
              Back to Prompt
            </Button>
            <div className="text-center w-full md:w-auto">
              <h1 className="text-xl font-semibold text-gray-800 dark:text-white">
                {generatedScript?.title}
              </h1>
            </div>
            <Button
              disabled={isLoading || generatedImages.length === 0 || isPublishing}
              onClick={handlePublish}
              className="bg-gradient-to-r from-primary to-secondary hover:opacity-90 rounded-xl text-lg"
            >
              {isPublishing ? statusMessage : "Publish to Twitter"}
            </Button>
          </div>
        </div>

        {/* Generation Logs */}
        {threadReport.length > 0 && (
          <div className="container mx-auto px-4 py-6 bg-white rounded-xl border shadow-sm">
            <h3 className="text-lg font-semibold text-foreground">Generation Logs</h3>
            <pre className="max-h-[300px] overflow-auto">
              {threadReport.map((report, index) => (
                <div key={index}>
                  Tweet {report.index + 1}: {report.success ? "Success" : "Failed"}
                  {report.error && <span className="text-red-500"> - {report.error}</span>}
                </div>
              ))}
            </pre>
          </div>
        )}

        {isLoading && (
          <div className="w-full bg-gray-200 text-center py-2">
            {statusMessage}
          </div>
        )}

        {/* Threads */}
        <div className="container mx-auto px-4 py-6">
          <TweetThread tweets={tweets} />
        </div>
      </section>
    </main>
  );
};

export default Thread;